name: First Workflow
on: push
jobs:
  first:
    runs-on: ubunt-latest
    steps:
      - name: Lint
        run: npm lint
      - name: Test
        run: npm test
      - name: Build
        run: npm build
      - name: Deploy
        run: echo "Deploying"