name: First Workflow
on: push
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run uild
      - name: Deploy
        run: echo "Deploying"